# Generated by Django 3.2.4 on 2023-04-01 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_alter_category_options_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='coordinates',
            field=models.CharField(default='0 0', max_length=255),
            preserve_default=False,
        ),
    ]
